import { audioKey } from "./hash.js";
import { toSpeech } from "./furigana.js";

// Pre-rendered VOICEVOX clips live in public/audio/<key>.wav (generated by
// scripts/build_audio_manifest.mjs + scripts/voicevox_batch_synth.py). When a
// clip is missing we fall back to the browser's own Japanese voice, so the app
// is useful with zero setup and better once the clips exist.
const base = import.meta.env.BASE_URL || "/";
const missing = new Set();
let current = null;

// Shared so every "play slowly" control in the app uses the same speed.
export const SLOW_RATE = 0.6;

export function stop() {
  if (current) {
    current.onended = null;
    current.onerror = null;
    current.pause();
    current = null;
  }
  try {
    window.speechSynthesis?.cancel();
  } catch {
    /* no speech synthesis available */
  }
}

function speakBrowser(text, rate) {
  return new Promise((resolve) => {
    try {
      if (!window.speechSynthesis) return resolve();
      const utter = new SpeechSynthesisUtterance(toSpeech(text));
      utter.lang = "ja-JP";
      utter.rate = 0.9 * rate;
      utter.onend = () => resolve();
      utter.onerror = () => resolve();
      window.speechSynthesis.speak(utter);
    } catch {
      resolve();
    }
  });
}

// Resolves when playback finishes, so callers can chain lines of a dialogue.
export function play(text, { rate = 1 } = {}) {
  const phrase = toSpeech(text);
  if (!phrase) return Promise.resolve();
  stop();

  const key = audioKey(phrase);
  if (missing.has(key)) return speakBrowser(text, rate);

  return new Promise((resolve) => {
    const audio = new Audio(`${base}audio/${key}.wav`);
    audio.playbackRate = rate;
    current = audio;
    audio.onended = () => {
      if (current === audio) current = null;
      resolve();
    };
    audio.play().catch(() => {
      // No clip rendered for this phrase yet — remember, and use the browser voice.
      missing.add(key);
      if (current === audio) current = null;
      speakBrowser(text, rate).then(resolve);
    });
  });
}

export function speak(text, opts) {
  play(text, opts);
}

// Plays a list of lines in order. Returns a cancel function; onIndex reports
// which line is sounding so the UI can highlight it.
export function playAll(texts, { rate = 1, gap = 350, onIndex } = {}) {
  let cancelled = false;
  (async () => {
    for (let i = 0; i < texts.length; i++) {
      if (cancelled) break;
      onIndex?.(i);
      await play(texts[i], { rate });
      if (cancelled) break;
      await new Promise((r) => setTimeout(r, gap));
    }
    if (!cancelled) onIndex?.(-1);
  })();

  return () => {
    cancelled = true;
    stop();
    onIndex?.(-1);
  };
}

export function clipUrl(text) {
  return `${base}audio/${audioKey(toSpeech(text))}.wav`;
}
